# Generated by Django 3.1.2 on 2021-10-27 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('rating', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[posts.service.validate_image])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_post', to='comments.comment')),
            ],
        ),
    ]
