# Generated by Django 3.1.2 on 2021-10-27 17:45

from django.db import migrations, models
import posts.service


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211027_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/%Y/%m/%d/', validators=[posts.service.validate_image]),
        ),
    ]
